server:
  port: ${SUBMISSION_SERVICE_PORT:8082}

spring:
  application:
    name: SUBMISSION-SERVICE
  data:
    mongodb:
      uri: ${MONGODB_URI_SUBMISSION}
eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
