server:
  port: ${SUBMISSION_SERVICE_PORT:8082}

spring:
  application:
    name: SUBMISSION-SERVICE
  data:
    mongodb:
      uri: ${MONGODB_URI_SUBMISSION:mongodb+srv://anvithsg2004:Ani%402004@cluster0.xf9on0f.mongodb.net/SUBMISSION?retryWrites=true&w=majority&appName=Cluster0}
eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health
