server:
  port: ${USER_SERVICE_PORT:8080}

spring:
  application:
    name: USER-SERVICE
  data:
    mongodb:
      uri: ${MONGODB_URI_USER}
eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

