server:
  port: ${USER_SERVICE_PORT:8080}

spring:
  application:
    name: USER-SERVICE
  data:
    mongodb:
      uri: ${MONGODB_URI_USER:mongodb+srv://anvithsg2004:Ani%402004@cluster0.xf9on0f.mongodb.net/USER?retryWrites=true&w=majority&appName=Cluster0&connectTimeoutMS=30000&timeoutMS=30000}
eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health
