server:
  port: ${TASK_SERVICE_PORT:8081}

spring:
  application:
    name: TASK-SERVICE
  data:
    mongodb:
      uri: ${MONGODB_URI_TASK}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
